module.exports = typeMapping = {
  form:         {template: "form"},
  errors:       {template: "errors"},
  submit:       {template: "submit",   htmlInputType: "submit"},
  string:       {template: "input",    htmlInputType: "string"},
  password:     {template: "input",    htmlInputType: "password"},
  email:        {template: "input",    htmlInputType: "email"},
  url:          {template: "input",    htmlInputType: "url"},
  tel:          {template: "input",    htmlInputType: "tel"},
  search:       {template: "input",    htmlInputType: "search"},
  uuid:         {template: "input",    htmlInputType: "text"},
  boolean:      {template: "checkbox", htmlInputType: "checkbox"},
  text:         {template: "text"},
  file:         {template: "file",     htmlInputType: "file"},
  hidden:       {template: "input",    htmlInputType: "hidden"},
  integer:      {template: "input",    htmlInputType: "number"},
  float:        {template: "input",    htmlInputType: "number"},
  decimal:      {template: "input",    htmlInputType: "number"},
  range:        {template: "input",    htmlInputType: "range"},
  # datetime:     {template: "datetime"},
  # date:         {template: "datetime"},
  # time:         {template: "datetime"},
  select:       {template: "select"},
  multiselect:  {template: "select"},
  typeahead:    {template: "typeahead"},
  # radioButtons: {template: "radioButtons"},
  # checkBoxes:   {template: "checkBoxes"},
  # country:      {template: "country"},
  # timeZone:     {template: "timeZone"},
}