module.exports = {
  form: {component: "form"},
  errors: {component: "errors"},
  submit: {component: "submit",   htmlInputType: "submit"},
  string: {component: "input",    htmlInputType: "string"},
  password: {component: "input",    htmlInputType: "password"},
  email: {component: "input",    htmlInputType: "email"},
  url: {component: "input",    htmlInputType: "url"},
  tel: {component: "input",    htmlInputType: "tel"},
  // search:       {component: "input",    htmlInputType: "search"},
  // uuid:         {component: "input",    htmlInputType: "text"},
  boolean: {component: "checkbox", htmlInputType: "checkbox"},
  text: {component: "text"},
  file: {component: "file",     htmlInputType: "file"},
  // hidden:       {component: "input",    htmlInputType: "hidden"},
  // integer:      {component: "input",    htmlInputType: "number"},
  float: {component: "number"},
  // decimal:      {component: "input",    htmlInputType: "number"},
  // range:        {component: "input",    htmlInputType: "range"},
  switch: {component: "switch"},
  // datetime:     {component: "datetime"},
  // date:         {component: "datetime"},
  time: {component: "timepicker"},
  select: {component: "select"},
  color: {component: "color"},
  // radioButtons: {component: "radioButtons"},
  // checkBoxes:   {component: "checkBoxes"},
  // country:      {component: "country"},
  // timeZone:     {component: "timeZone"},
}
