module.exports = {
  string: { component: 'Input', htmlInputType: 'string' },
  password: { component: 'Input', htmlInputType: 'password' },
  email: { component: 'Input', htmlInputType: 'email' },
  url: { component: 'Input', htmlInputType: 'url' },
  tel: { component: 'Input', htmlInputType: 'tel' },
  // search: { component: 'Input', htmlInputType: 'search' },
  // uuid: { component: 'Input', htmlInputType: 'text' },
  boolean: { component: 'Checkbox', htmlInputType: 'checkbox' },
  text: { component: 'Text' },
  file: { component: 'File', htmlInputType: 'file' },
  // hidden: { component: 'Input', htmlInputType: 'hidden' },
  // integer: { component: 'Input', htmlInputType: 'number' },
  float: { component: 'Number' },
  // decimal: { component: 'Input', htmlInputType: 'number' },
  // range: { component: 'Input', htmlInputType: 'range' },
  switch: { component: 'Switch' },
  // datetime: { component: 'Datetime' },
  // date: { component: 'Datetime' },
  time: { component: 'Timepicker' },
  select: { component: 'Select' },
  color: { component: 'Color' },
  // radioButtons: { component: 'RadioButtons' },
  // checkBoxes: { component: 'CheckBoxes' },
  // country: { component: 'Country' },
  // timeZone: { component: 'TimeZone' },
}
